[package]
name = "zjstatus-hints"
version = "0.1.2"
authors = ["Maddison Hellstrom <hi@maddison.io>", "Brooks J Rady <b.j.rady@gmail.com>"]
edition = "2021"
license = "MIT"
rust-version = "1.84"

[dependencies]
ansi_term = "0.12"
zellij-tile = "0.42.2"
zellij-tile-utils = "0.42.2"
